XBotCore:
  config_path: "external/DebrisRemovalTask/configs/centauro.yaml"

XBotInterface:
  urdf_path: "configs/ADVR_shared/centauro/urdf/centauro.urdf"
  srdf_path: "configs/ADVR_shared/centauro/srdf/centauro.srdf"
  joint_map_path: "configs/ADVR_shared/centauro/joint_map/centauro_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample", "IkRosSMPub", "OpenSotIk", "Grasp"]
  io_plugins: ["IkRosIo", "JointStateRemapper"]
  
NRTPlugins:
  plugins: ["ManipulationPlugin"]

WebServer:
  enable: "true"
  address: "127.0.0.1"
  port: "8081"

SimulationOptions:
  verbose_mode: "false"
